// Cache bump v7 – forces browser to fetch fresh files
self.addEventListener("install",(e)=>{
  self.skipWaiting();
  e.waitUntil(
    caches.open("invoice-cache-v7").then(cache=>cache.addAll([
      "./","index.html","style.css","app.js","manifest.json",
      "icons/icon-192.png","icons/icon-512.png"
    ]))
  );
});
self.addEventListener("activate",(e)=>{
  e.waitUntil(
    caches.keys().then(keys=>Promise.all(keys.filter(k=>k!=="invoice-cache-v7").map(k=>caches.delete(k))))
    .then(()=>self.clients.claim())
  );
});
self.addEventListener("fetch",(e)=>{
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});
